# Install CA certificates
- name: Install legacy.crt
  ansible.builtin.get_url:
    url: https://password.corp.redhat.com/legacy.crt
    dest: /etc/pki/ca-trust/source/anchors/legacy.crt
  register: result
  until: result is succeeded
  retries: 3
  delay: 5

- name: Install legacy.crt
  ansible.builtin.get_url:
    url: https://password.corp.redhat.com/legacy.crt
    dest: /etc/openldap/cacerts/legacy.crt
  register: result
  until: result is succeeded
  retries: 3
  delay: 5

- name: Install RH-IT-Root-CA.crt
  ansible.builtin.get_url:
    url: https://password.corp.redhat.com/RH-IT-Root-CA.crt
    dest: /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
  register: result
  until: result is succeeded
  retries: 3
  delay: 5

- name: Install RH-IT-Root-CA.crt
  ansible.builtin.get_url:
    url: https://password.corp.redhat.com/RH-IT-Root-CA.crt
    dest: /etc/openldap/cacerts/RH-IT-Root-CA.crt
  register: result
  until: result is succeeded
  retries: 3
  delay: 5

- name: Rehash cacerts
  ansible.builtin.command:
    cmd: openssl rehash /etc/openldap/cacerts

- name: Update CA Trust
  ansible.builtin.command:
    cmd: update-ca-trust
