- name: Clone a dot files repo
  ansible.builtin.git:
    repo: "{{ dot_repo }}"
    dest: "{{ dot_files_dst }}"
    force: true

# https://github.com/nleiva/dotfiles#install
- name: Install dot files
  ansible.builtin.command: "{{ dot_files_dst }}/install.sh"

# - name: Disable desktop effects in Cinnamon
#   community.general.dconf:
#     key: "/org/cinnamon/desktop-effects"
#     value: "false"
#     state: present

- name: Install GNOME Extensions
  ansible.builtin.include_tasks: gnome_extensions.yml
