- name: Add Code Server Repo
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code repo
    baseurl: "{{ vscode_repo }}"
    gpgkey: "{{ vscode_key }}"
    gpgcheck: true

- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: "{{ epel_key }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install EPEL repo
  ansible.builtin.yum:
    name: "{{ epel_repo }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10

# - name: Install RPM Fusion repo
#   ansible.builtin.yum:
#     name: "{{ rpmfusion_repo }}"
#     state: present
#   register: result
#   until: result is succeeded
#   retries: 5
#   delay: 10

- name: Enable additonal RHEL repositories
  community.general.rhsm_repository:
    name: "{{ rhel_repos }}"
    state: enabled

- name: Install Tailscale repo
  ansible.builtin.get_url:
    url: "{{ tailscale_repo }}"
    dest: /etc/yum.repos.d/tailscale.repo
  register: result
  until: result is succeeded
  retries: 3
  delay: 5

- name: Remove the flathub remote from the system installation
  community.general.flatpak_remote:
    name: flathub
    state: absent
    method: user
  become: false

- name: Add the Flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "{{ flathub }}"
    method: user
  become: false
