- name: Update all packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    exclude: "{{ exclude_pkgs }}"

- name: Install base packages
  ansible.builtin.dnf:
    name: "{{ base_software[ansible_distribution] | union(common_software) }}"
    state: present
  register: package_check
  until: package_check is not failed
  retries: 4
  delay: 5

- name: Install apps from flathub for current user
  community.general.flatpak:
    name: "{{ flathub_apps }}"
    state: present
    method: user
    remote: flathub
  become: false
  tags: flatpak

- name: Repair Flatpak
  ansible.builtin.command:
    cmd: flatpak repair
  tags: flatpak

- name: Update Flatpak
  ansible.builtin.command:
    cmd: flatpak update -y
  become: false
  tags: flatpak

- name: Install Python dependencies within a user home directory
  ansible.builtin.pip:
    name: "{{ python_libraries }}"
    executable: pip3
    extra_args: --user
  become: false
